- src/index.js
- types/index.d.ts
As discussed in #82.
I'm not sure for the Flow export, I've seen that in Flow the syntax is `export type { SomeType }` whereas in typescript we would do `export { SomeType }` like a JS value. I hope the `export * from` syntax in Flow also exports types?
> Export all TypeScript and Flow types from definitions.{js|d.ts}

- examples/with-graphql-tools/README.md
- examples/with-graphql-tools/index.js
I just notice that example use 3001 instead of 3000 that tell in console 😐
> fix(example) with-graphql-tools launch on wrong port number

- package.json
- src/EnumTypeComposer.d.ts
- src/InputTypeComposer.d.ts
- src/InterfaceTypeComposer.d.ts
- src/Resolver.d.ts
- src/SchemaComposer.d.ts
- src/TypeComposer.d.ts
- src/TypeMapper.d.ts
- src/TypeStorage.d.ts
- src/__tests__/typedefs/Others.spec.ts
- src/__tests__/typedefs/Resolver.spec.ts
- src/__tests__/typedefs/TypeComposer.spec.ts
- src/__tests__/typedefs/mock-typedefs.ts
- src/__tests__/typescript-typedef.spec.ts
- src/index.d.ts
- src/utils/filterByDotPaths.d.ts
- src/utils/is.d.ts
- src/utils/projection.d.ts
- src/utils/toDottedObject.d.ts
- src/utils/toInputObjectType.d.ts
- tsconfig.json
- tslint.json
- yarn.lock
Adoptive commit
When using Mongoose plugin, i often get the source interface in the context arg of resolvers so i decided to look into the issue and brought this up. Please review and ask any question.
@nodkz @toverux you might want to check this changes...
This is just a test commit for review to see if i am getting the idea right.
```typescript
import { SchemaComposer } from '../index';
import { TypeComposer } from '../TypeComposer';
interface Person {
uid: string;
name: string;
nickName: string;
age: number;
}
interface Context {
req: any;
res: any;
uid: string;
}
// works for cases where u create your instance of
const schemaComposer = new SchemaComposer<Context>();
// Person from this schemaComposer gets the context defined for that schemaComposer
const Person = …
```
> WIP: fix(typedefs): fix `source` being resolved as `context`

- src/Resolver.d.ts
- src/TypeComposer.d.ts
- src/__tests__/typedefs/TypeComposer.spec.ts
* fix(TypeScript): update typescript type annotations that were missed out for (#134)
Actually, Added `TSource` to `ComposeOutputType`.
i.e. changing `ComposeOutputType<TContext>` to `ComposeOutputType<TSource, TContext>`
* refactor(TypeScript): at `ComposeFieldConfig`, swap (() => ...) to Thunk<...>
> fix(TypeScript): update typescript type annotations that were missed (#134)

- src/InterfaceTypeComposer.d.ts
- src/Resolver.d.ts
- src/TypeComposer.d.ts
- src/__tests__/typedefs/Resolver.spec.ts
- src/__tests__/typedefs/TypeComposer.spec.ts
- src/__tests__/typedefs/mock-typedefs.ts
While working on TypeDefs for #134 this solutions didn't occur to me. I thought we could review. You can see more use cases in the examples
* feat(typedefs): add `TSource` support in `InterfaceTypeComposer`
* feat(typedefs): add `TArgsMap` support to `ComposeFieldConfig`
```typescript
interface Field1 {
arg1: string;
arg2: number;
}
interface FieldsArgsMap {
field1: Field1;
field2: {
arg3: boolean;
arg4: any;
};
}
PersonTC.setField('field1', {
type: 'Int',
resolve: (source, args) => {
args.arg1 = 'string';
args.arg1 = 3;
},
});
PersonTC.setField<Field1>('field1', {
type: 'Int',
resolve: (source, args) => {
args.arg1 = 'string';
// args.arg1 = 3
},
});
PersonTC.addFields({
field1: {
type: 'Int',
resolve: (source, args) => {
args.arg1 = 'string';
args.arg1 = 44;
},
},
field2: {
type: …
```
> feat(TypeScript): add `TArgsMap` to `ComposeFieldConfig`, `TSource` to `InterfaceTC`

- src/type/__tests__/date-test.js
- src/type/date.js
Allow timestamps (e.g. the result from `Date.now()`) as GraphQLDate values.
> Add support for Date.now() to GraphQLDate

- src/utils/__tests__/toInputObjectType-test.js
- src/utils/toInputObjectType.js
Follow-up to #141.
Make `toInputObjectType` handle InterfaceType fields.
> Allow InterfaceType fields in conversion to InputObjectType

- src/TypeMapper.js
Adds `astNode` field, mainly for compatibility with `graphql-tools`-created schemas. Also fix small typo.
Fixes #147
> fix: add astNode in type creation

- src/InterfaceTypeComposer.d.ts
- src/InterfaceTypeComposer.js
- src/utils/toInputObjectType.js
This adds input type methods to `InterfaceTypeComposer`, same as the ones on `TypeComposer`.
> Add InputType methods to InterfaceTypeComposer

- src/utils/__tests__/toInputObjectType-test.js
- src/utils/toInputObjectType.js
Currently in `toInputObjectType` the names of the created ITCs are prefixed with the names of their upper-level TCs. This can lead to very long names for deeper nesting levels, and also seems unnecessary since the TC name should already be unique. But I'm not sure if anyone could rely on this naming scheme?
> Don't add outputTypeName to InputTypeComposer prefix

- src/utils/__tests__/projection-test.js
- src/utils/projection.d.ts
- src/utils/projection.js
Currently it is possible to specify a `projection` field property -- does it make sense to also allow specifying projection as an extension?
(I also renamed `context` to `info` since I have found it a bit confusing since `context` usually is the third resolver arg?)
> Allow projection as an extension

- src/InputTypeComposer.d.ts
- src/InputTypeComposer.js
- src/InterfaceTypeComposer.js
- src/ObjectTypeComposer.js
- src/__tests__/InputTypeComposer-test.js
- src/__tests__/InterfaceTypeComposer-test.js
- src/__tests__/ObjectTypeComposer-test.js
This PR changes the behavior of `extendField` to shallow-merge `extensions` instead of overwriting.
I am not very good with Flow - could you check what needs to be changed with the `setField` call? Thank you!
Fixes #177
> Extend field extensions in extendField

- src/InputTypeComposer.js
- src/InterfaceTypeComposer.js
- src/ObjectTypeComposer.js
Because of https://github.com/graphql-compose/graphql-compose/commit/7c8dcd8102225be7a85b4696063805971975a1c0 is it correct to assume that we can now use `getField` instead of `getFieldConfig` in `extendField` methods (to not resolve types early)?
> Use getField instead of getFieldConfig in extendField

- src/SchemaComposer.js
Don't mutate `BUILT_IN_DIRECTIVES` when adding directives.
Would it be possible to also release a v6 with this? This would be awesome, thanks so much!
> Don't mutate built-in directives

- src/InputTypeComposer.d.ts
- src/InputTypeComposer.js
- src/InterfaceTypeComposer.d.ts
- src/InterfaceTypeComposer.js
- src/ObjectTypeComposer.d.ts
- src/ObjectTypeComposer.js
- src/TypeMapper.d.ts
- src/TypeMapper.js
- src/__tests__/ObjectTypeComposer-test.js
- src/__tests__/TypeMapper-test.js
- src/__tests__/github_issues/231-test.js
As discussed.
The test is not mentioning circular references at all, contrarily to my issue.
In my codebase, that's what made the problem visible, but actually you just have to clone a resolver for this to happen.
I also test that `type` thunks are not called, just in case, but that currently not the case, only `args` thunks are called while cloning.
Try replacing `aResolver.clone()` with the workaround in the function I posted in the issue and the test passes :)
> Add test for #231

- src/SchemaComposer.js
- src/__tests__/SchemaComposer-test.js
[graphql-js](https://github.com/graphql/graphql-js/blob/v14.6.0/src/utilities/buildASTSchema.js#L178) `buildSchema` allows null root query types and will build the schema. This replicates this behaviour here.
> fix: allow empty root query

- src/__tests__/github_issues/246-test.js
- src/utils/schemaPrinter.js
`.toSDL({exclude: ['String']})` does not exclude String from schema SDL if it has also been defined in a directive definition.
> fix: exclude scalars defined in directives

- src/EnumTypeComposer.d.ts
- src/EnumTypeComposer.js
- src/InputTypeComposer.d.ts
- src/InputTypeComposer.js
- src/InterfaceTypeComposer.d.ts
- src/InterfaceTypeComposer.js
- src/ListComposer.d.ts
- src/ListComposer.js
- src/NonNullComposer.d.ts
- src/NonNullComposer.js
- src/ObjectTypeComposer.d.ts
- src/ObjectTypeComposer.js
- src/ScalarTypeComposer.d.ts
- src/ScalarTypeComposer.js
- src/ThunkComposer.d.ts
- src/ThunkComposer.js
- src/UnionTypeComposer.d.ts
- src/UnionTypeComposer.js
- src/__tests__/EnumTypeComposer-test.js
- src/__tests__/InputTypeComposer-test.js
- src/__tests__/InterfaceTypeComposer-test.js
- src/__tests__/ListComposer-test.js
- src/__tests__/NonNullComposer-test.js
- src/__tests__/ObjectTypeComposer-test.js
- src/__tests__/ScalarTypeComposer-test.js
- src/__tests__/ThunkComposer-test.js
- src/__tests__/UnionTypeComposer-test.js
It helps to simplify your code and make it more readable:
```diff
const UserTC = schemaComposer.createObjectTC(`type User { name: String }`);
schemaComposer.Query.addFields({
-  users: { type: UserTC.getTypeNonNull().getTypePlural() }
+  users: { type: UserTC.NonNull.List }
});
```
> Modificators via getters

- .travis.yml
- README.md
- package.json
- src/InterfaceTypeComposer.js
- src/TypeMapper.js
- src/__tests__/InterfaceTypeComposer-test.js
- src/utils/schemaPrinter.js
From GraphQL 15.0.0 Interfaces can now implement other interfaces. So adding the following helper methods to `InterfaceTypeComposer`:
- `getInterfaces()`
- `getInterfacesTypes()`
- `setInterfaces()`
- `hasInterface()`
- `addInterface()`
- `addInterfaces()`
- `removeInterface()`
Closes #251
> feat: support for adding interfaces to other interfaces

- src/SchemaComposer.d.ts
- src/SchemaComposer.js
- src/__tests__/SchemaComposer-test.js
Closes https://github.com/graphql-compose/graphql-compose/issues/293
This PR adds a `keepUnusedTypes` config option to `buildSchema()`, which defaults to false, so there is no breaking change to this change.
See the unit test added.
> feat(buildSchema): add option to keep unused types

- src/__tests__/github_issues/314-test.js
- src/utils/configToDefine.js
This PR fixes a bug with thunk composers, outlined in #314 
The root cause is this thunk composer:
https://github.com/graphql-compose/graphql-compose/blob/ffeeab6de8178c7fd34ee96bce308c67caba7ae2/src/utils/configToDefine.js#L146-L157
When this thunk is invoked, the actual value of `fc.args[argName].type` points to the same exact thunk composer because `fc.args` is re-assigned on the last line.
Fixes #314
> fix: stack overflow for fields defined as thunks

- src/utils/configToDefine.js
Hey @nodkz 👋 
We've faced significant performance regression in Gatsby when building a huge schema on v7. For v6 that schema took 12 seconds to build, for v7 - 66 seconds (this schema has 50000+ values in several of its enum types - don't ask why 😅).
I've narrowed down the problem to expensive `.find()` calls when assigning `astNode` which makes corresponding methods O(N^2). For 50000+ values that gets pretty messy.
This PR replaces those `.find()` calls in loops with quick map lookups which makes is O(N). And in my tests that beast schema builds in 12 seconds again with this PR.
> perf: optimize expensive .find() calls within loops

- src/InterfaceTypeComposer.d.ts
- src/InterfaceTypeComposer.js
- src/ObjectTypeComposer.d.ts
- src/ObjectTypeComposer.js
- src/utils/__tests__/toInputType-test.js
- src/utils/toInputType.d.ts
- src/utils/toInputType.js
In the previous version of `graphql-compose` (v6) it was possible to skip unions when building input types. We are still relying on this behavior in Gatsby (and [actually miss it a lot](https://github.com/gatsbyjs/gatsby/pull/29090#discussion_r572370812))
`graphql-compose` v7 has `fallbackType` option but it doesn't allow you to skip the field altogether - it will still add the field with this fallback type.
This PR adds a simple workaround to make omitting unions possible again. As long as you pass `null` in `fallbackType` it will effectively omit fields of the union type when building input types.
> feat: allow skipping unions when building input types

- src/InterfaceTypeComposer.d.ts
GraphQL supports interface inheritance as of 15.0.0. This seems to be working fine with `graphql-compose` without any code changes (at least [our test](https://github.com/gatsbyjs/gatsby/blob/33e0f860b5eb9efee64929df000e854ec664a276/packages/gatsby/src/schema/__tests__/build-schema.js#L270-L276) in Gatsby passes).
But typescript definitions do not reflect that. This PR simply updates them.
> fix: update .d.ts for InterfaceTypeComposer

- docs/basics/understanding-relations.md
As discussed [in this PR](https://github.com/graphql-compose/graphql-compose.github.io/pull/34), we're moving [the original improvement PR](https://github.com/graphql-compose/graphql-compose.github.io/pull/33) to the current repo.
Original comment:
> I've added lots of small improvements. Mainly adding missing articles ("the", "a", etc.) and rewriting parts of the text to make it more readable. I hope it helps improving the docs :)
> Improve language and grammar

- src/InputTypeComposer.ts
- src/InterfaceTypeComposer.ts
- src/ObjectTypeComposer.ts
- src/SchemaComposer.ts
- src/UnionTypeComposer.ts
- src/__tests__/SchemaComposer-test.ts
- src/utils/getFromSchema.ts
- src/utils/schemaPrinter.ts
- src/utils/sortTypes.ts
I know this will very likely need refactoring before being accepted, but I want some input if this feature is desired.
By default, when you call `mySchemaComposer.toSDL()`, all objects are printed to a string, sorted by the name of the entity (be it scalar, enum, interface, input, object or union). I think a much more human friendly way of printing it is:
1. Scalar types
2. Root Object types (Query, Mutation, Subscription)
3. Enum types
4. Interface types
5. Input types
6. Object types
7. Union types
Actually I have almost no experience in GraphQL, I'm starting to learn and use it, but anyway I didn't like that the default way of printing mixes all these entity types. Maybe for an experienced GraphQL user the "ideal" way to sort entities when printing could be different, and the default …
> feat(toSDL): allow custom sorting and sorting by entity types

- docs/plugins/plugin-mongoose.md
With the composeWithMongoose -> composeMongoose change, discriminators didn't follow. Updating the docs to reflect the actual name of the function.
> fix(docs): composeMongooseDiscriminators -> composeWithMongooseDiscriminators

- src/utils/typeHelpers.ts
When using `ObjectTypeComposer.addInterface` with argument being `InterfaceTypeComposer` that reference fields of types that were not created yet we are getting errors. This happens because of this chain:
https://github.com/graphql-compose/graphql-compose/blob/659f821953acd3dbc1aba098a543058f7aa1018c/src/ObjectTypeComposer.ts#L1411
https://github.com/graphql-compose/graphql-compose/blob/659f821953acd3dbc1aba098a543058f7aa1018c/src/ObjectTypeComposer.ts#L1402
https://github.com/graphql-compose/graphql-compose/blob/659f821953acd3dbc1aba098a543058f7aa1018c/src/utils/typeHelpers.ts#L340
https://github.com/graphql-compose/graphql-compose/blob/659f821953acd3dbc1aba098a543058f7aa1018c/src/utils/typeHelpers.ts#L308
The last one tries to "instantiate" it as `GraphQLType` type, but depending on …
> fix: don't try to instantiate GraphQLType when getting name of named type composer

- docs/intro/quick-start.md
`...client requests some data, and *tipically* makes a second or even third request...`
to
`...client requests some data, and *typically* makes a second or even third request...`
> correct spelling error in Quick Start Guide

- .vscode/settings.json
- src/__tests__/github_issues/407-test.ts
- src/utils/definitionNode.ts
- yarn.lock
Fixes #407 by falling back to `toValueNode` if `astFromValue` fails.
> fix: handle scalar arguments with object default values
